In [1]:

import torch

print("PyTorch version:", torch.__version__)

PyTorch version: 2.1.1+cpu


In [2]:
idx= torch.tensor([1,2,3])
out_dim=5

In [3]:
num_idx=len(idx)+1

In [4]:
num_idx

4

In [7]:
torch.manual_seed(123)


In [8]:
embedding_layer= torch.nn.Embedding(num_idx, out_dim)

In [9]:
embedding_layer.weight

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  1.5810],
        [ 1.3010,  1.2753, -0.2010, -0.1606, -0.4015],
        [ 0.6957, -1.8061, -1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096, -0.4076,  0.7953]], requires_grad=True)

In [10]:
embedding_layer(torch.tensor([2]))

tensor([[ 0.6957, -1.8061, -1.1589,  0.3255, -0.6315]],
       grad_fn=<EmbeddingBackward0>)

In [11]:
embedding_layer(idx)

tensor([[ 1.3010,  1.2753, -0.2010, -0.1606, -0.4015],
        [ 0.6957, -1.8061, -1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096, -0.4076,  0.7953]],
       grad_fn=<EmbeddingBackward0>)

## Using nn.Linear

* Now, we will demonstrate that the embedding layer above accomplishes exactly the same as nn.Linear layer on a one-hot encoded representation in PyTorch
* First, let's convert the token IDs into a one-hot representation:

In [12]:
onehot = torch.nn.functional.one_hot(idx)
onehot

tensor([[0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [13]:
torch.manual_seed(123)
linear = torch.nn.Linear(num_idx, out_dim, bias=False)
linear.weight

Parameter containing:
tensor([[-0.2039,  0.0166, -0.2483,  0.1886],
        [-0.4260,  0.3665, -0.3634, -0.3975],
        [-0.3159,  0.2264, -0.1847,  0.1871],
        [-0.4244, -0.3034, -0.1836, -0.0983],
        [-0.3814,  0.3274, -0.1179,  0.1605]], requires_grad=True)

In [14]:
linear.weight = torch.nn.Parameter(embedding_layer.weight.T)


In [15]:
linear(onehot.float())


tensor([[ 1.3010,  1.2753, -0.2010, -0.1606, -0.4015],
        [ 0.6957, -1.8061, -1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096, -0.4076,  0.7953]], grad_fn=<MmBackward0>)

In [16]:
embedding_layer(idx)


tensor([[ 1.3010,  1.2753, -0.2010, -0.1606, -0.4015],
        [ 0.6957, -1.8061, -1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096, -0.4076,  0.7953]],
       grad_fn=<EmbeddingBackward0>)