In [85]:
from importlib.metadata import version

print("torch version: ", version("torch"))
print("tiktoken version : ", version("tiktoken"))

torch version:  2.1.1
tiktoken version :  0.3.3


In [86]:
!pip install torch

In [ ]:
version("torch")

'2.1.1'

Tokenizing text


In [ ]:
import os
import urllib.request




In [ ]:
with open("text.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

In [ ]:
len(raw_text)

20479

In [ ]:
raw_text

'I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped his painting, married a rich widow, and established himself in a villa on the Riviera. (Though I rather thought it would have been Rome or Florence.)\n\n"The height of his glory"--that was what the women called it. I can hear Mrs. Gideon Thwing--his last Chicago sitter--deploring his unaccountable abdication. "Of course it\'s going to send the value of my picture \'way up; but I don\'t think of that, Mr. Rickham--the loss to Arrt is all I think of." The word, on Mrs. Thwing\'s lips, multiplied its _rs_ as though they were reflected in an endless vista of mirrors. And it was not only the Mrs. Thwings who mourned. Had not the exquisite Hermia Croft, at the last Grafton Gallery show, stopped me before Gisburn\'s "Moon-dancers" to say, with tears in her eyes: "We shall not look upon its like again"?\n\nWell!--even 

In [ ]:
type(raw_text)

str

In [ ]:
raw_text[:100]

'I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no g'

The pattern r'(\s)' is a regular expression:
    
   * r before the string indicates a raw    string, meaning backslashes are treated literally.

   * (\s) matches any whitespace character (like spaces, tabs, or newlines). The parentheses around \s create a capturing group, which means the matched whitespace characters will be included in the resulting list.

In [ ]:
import re

text= "Hello, world. My name is Mukund Agarwalla"
result= re.split(r'(\s)', text)

result

['Hello,',
 ' ',
 'world.',
 ' ',
 'My',
 ' ',
 'name',
 ' ',
 'is',
 ' ',
 'Mukund',
 ' ',
 'Agarwalla']

r before the string denotes a raw string, meaning backslashes are treated literally and not as escape characters.
   
   * ([,.]|\s) is the regular expression pattern used for splitting the text.
    
   * [,.] matches any comma , or period . character. The square brackets [ ] define a character class that matches any one of the characters inside them.

   * \s matches any whitespace character (spaces, tabs, newlines, etc.).

   * | is the logical OR operator in regular expressions, meaning it matches either the pattern on its left or the pattern on its right.

   * () around [,.]|\s create a capturing group, meaning the matched delimiters (commas, periods, and whitespaces) will be included in the resulting list.

In [ ]:
result= re.split(r'([,.]|\s)', text)

result

['Hello',
 ',',
 '',
 ' ',
 'world',
 '.',
 '',
 ' ',
 'My',
 ' ',
 'name',
 ' ',
 'is',
 ' ',
 'Mukund',
 ' ',
 'Agarwalla']

In [ ]:
result= [item for item in result if item.split()]
print(result)

['Hello', ',', 'world', '.', 'My', 'name', 'is', 'Mukund', 'Agarwalla']


In [ ]:
preprocessed= re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
preprocessed= [item for item in preprocessed if item.strip()]
print(preprocessed[:30])

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in']


In [ ]:
len(preprocessed)

4690

In [ ]:
all_words= sorted(set(preprocessed))

In [ ]:
vocab_size= len(all_words)
vocab_size

1130

   * enumerate is a built-in function that takes an iterable (in this case, all_words) and returns an iterator of tuples, where each tuple contains an index and the corresponding item from the iterable.
   * For example, if all_words is ['apple', 'banana', 'cherry'], enumerate(all_words) produces:

[(0, 'apple'), (1, 'banana'), (2, 'cherry')]

In [ ]:
vocab = {token:integer for integer,token in enumerate(all_words)}


In [ ]:
vocab

{'!': 0,
 '"': 1,
 "'": 2,
 '(': 3,
 ')': 4,
 ',': 5,
 '--': 6,
 '.': 7,
 ':': 8,
 ';': 9,
 '?': 10,
 'A': 11,
 'Ah': 12,
 'Among': 13,
 'And': 14,
 'Are': 15,
 'Arrt': 16,
 'As': 17,
 'At': 18,
 'Be': 19,
 'Begin': 20,
 'Burlington': 21,
 'But': 22,
 'By': 23,
 'Carlo': 24,
 'Chicago': 25,
 'Claude': 26,
 'Come': 27,
 'Croft': 28,
 'Destroyed': 29,
 'Devonshire': 30,
 'Don': 31,
 'Dubarry': 32,
 'Emperors': 33,
 'Florence': 34,
 'For': 35,
 'Gallery': 36,
 'Gideon': 37,
 'Gisburn': 38,
 'Gisburns': 39,
 'Grafton': 40,
 'Greek': 41,
 'Grindle': 42,
 'Grindles': 43,
 'HAD': 44,
 'Had': 45,
 'Hang': 46,
 'Has': 47,
 'He': 48,
 'Her': 49,
 'Hermia': 50,
 'His': 51,
 'How': 52,
 'I': 53,
 'If': 54,
 'In': 55,
 'It': 56,
 'Jack': 57,
 'Jove': 58,
 'Just': 59,
 'Lord': 60,
 'Made': 61,
 'Miss': 62,
 'Money': 63,
 'Monte': 64,
 'Moon-dancers': 65,
 'Mr': 66,
 'Mrs': 67,
 'My': 68,
 'Never': 69,
 'No': 70,
 'Now': 71,
 'Nutley': 72,
 'Of': 73,
 'Oh': 74,
 'On': 75,
 'Once': 76,
 'Only': 77,
 '

In [ ]:
type(vocab)

dict

In [ ]:
for i,s in vocab.items():
    print(f"{i} -> {s}")
  

! -> 0
" -> 1
' -> 2
( -> 3
) -> 4
, -> 5
-- -> 6
. -> 7
: -> 8
; -> 9
? -> 10
A -> 11
Ah -> 12
Among -> 13
And -> 14
Are -> 15
Arrt -> 16
As -> 17
At -> 18
Be -> 19
Begin -> 20
Burlington -> 21
But -> 22
By -> 23
Carlo -> 24
Chicago -> 25
Claude -> 26
Come -> 27
Croft -> 28
Destroyed -> 29
Devonshire -> 30
Don -> 31
Dubarry -> 32
Emperors -> 33
Florence -> 34
For -> 35
Gallery -> 36
Gideon -> 37
Gisburn -> 38
Gisburns -> 39
Grafton -> 40
Greek -> 41
Grindle -> 42
Grindles -> 43
HAD -> 44
Had -> 45
Hang -> 46
Has -> 47
He -> 48
Her -> 49
Hermia -> 50
His -> 51
How -> 52
I -> 53
If -> 54
In -> 55
It -> 56
Jack -> 57
Jove -> 58
Just -> 59
Lord -> 60
Made -> 61
Miss -> 62
Money -> 63
Monte -> 64
Moon-dancers -> 65
Mr -> 66
Mrs -> 67
My -> 68
Never -> 69
No -> 70
Now -> 71
Nutley -> 72
Of -> 73
Oh -> 74
On -> 75
Once -> 76
Only -> 77
Or -> 78
Perhaps -> 79
Poor -> 80
Professional -> 81
Renaissance -> 82
Rickham -> 83
Riviera -> 84
Rome -> 85
Russian -> 86
Sevres -> 87
She -> 88
Stroud -> 8

In [ ]:
for i,item in enumerate(vocab.items()):
    if i<50:
        print(item)

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)


## Putting it now all together into a tokenizer class

In [ ]:
class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int= vocab
        self.int_to_str= {i:s for s,i in vocab.items()}

    def encode(self, text):
        preprocessed= re.split(r'[,.?;:_!"()\']|--|\s', text)
        preprocessed= [item.strip() for item in preprocessed if item.strip()]
        ids=[self.str_to_int[s] for s in preprocessed]
        return ids
    
    def decode(self, ids):
        text= " ".join([self.int_to_str[i] for i in ids])
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text
    

In [ ]:
tokenizer= SimpleTokenizerV1(vocab)

text = """"It's the last he painted, you know," 
           Mrs. Gisburn said with pardonable pride."""
ids = tokenizer.encode(text)
print(ids)

[56, 850, 988, 602, 533, 746, 1126, 596, 67, 38, 851, 1108, 754, 793]


In [ ]:
tokenizer.decode(tokenizer.encode(text))

'It s the last he painted you know Mrs Gisburn said with pardonable pride'

### Adding special context tokens

* Some tokenizers use special tokens to help the LLM with additional context

* Some of these special tokens are

    * [BOS] (beginning of sequence) marks the beginning of text
    * [EOS] (end of sequence) marks where the text ends (this is usually used to concatenate multiple unrelated texts, e.g., two different Wikipedia articles or two different books, and so on)
    * [PAD] (padding) if we train LLMs with a batch size greater than 1 (we may include multiple texts with different lengths; with the padding token we pad the shorter texts to the longest length so that all texts have an equal length)
* [UNK] to represent words that are not included in the vocabulary

* Note that GPT-2 does not need any of these tokens mentioned above but only uses an <|endoftext|> token to reduce complexity

* The <|endoftext|> is analogous to the [EOS] token mentioned above

* GPT also uses the <|endoftext|> for padding (since we typically use a mask when training on batched inputs, we would not attend padded tokens anyways, so it does not matter what these tokens are)

* GPT-2 does not use an <UNK> token for out-of-vocabulary words; instead, GPT-2 uses a byte-pair encoding (BPE) tokenizer, which breaks down words into subword units which we will discuss in a later section

* We use the <|endoftext|> tokens between two independent sources of text:


In [ ]:
preprocessed

['I',
 'HAD',
 'always',
 'thought',
 'Jack',
 'Gisburn',
 'rather',
 'a',
 'cheap',
 'genius',
 '--',
 'though',
 'a',
 'good',
 'fellow',
 'enough',
 '--',
 'so',
 'it',
 'was',
 'no',
 'great',
 'surprise',
 'to',
 'me',
 'to',
 'hear',
 'that',
 ',',
 'in',
 'the',
 'height',
 'of',
 'his',
 'glory',
 ',',
 'he',
 'had',
 'dropped',
 'his',
 'painting',
 ',',
 'married',
 'a',
 'rich',
 'widow',
 ',',
 'and',
 'established',
 'himself',
 'in',
 'a',
 'villa',
 'on',
 'the',
 'Riviera',
 '.',
 '(',
 'Though',
 'I',
 'rather',
 'thought',
 'it',
 'would',
 'have',
 'been',
 'Rome',
 'or',
 'Florence',
 '.',
 ')',
 '"',
 'The',
 'height',
 'of',
 'his',
 'glory',
 '"',
 '--',
 'that',
 'was',
 'what',
 'the',
 'women',
 'called',
 'it',
 '.',
 'I',
 'can',
 'hear',
 'Mrs',
 '.',
 'Gideon',
 'Thwing',
 '--',
 'his',
 'last',
 'Chicago',
 'sitter',
 '--',
 'deploring',
 'his',
 'unaccountable',
 'abdication',
 '.',
 '"',
 'Of',
 'course',
 'it',
 "'",
 's',
 'going',
 'to',
 'send',
 't

In [ ]:
all_tokens= sorted(set(preprocessed))
all_tokens.extend(["<|endoftext|>","<|unk|>"])

In [ ]:
vocab= {token: integer for integer, token in enumerate(all_tokens)}

In [ ]:
vocab.items()

dict_items([('!', 0), ('"', 1), ("'", 2), ('(', 3), (')', 4), (',', 5), ('--', 6), ('.', 7), (':', 8), (';', 9), ('?', 10), ('A', 11), ('Ah', 12), ('Among', 13), ('And', 14), ('Are', 15), ('Arrt', 16), ('As', 17), ('At', 18), ('Be', 19), ('Begin', 20), ('Burlington', 21), ('But', 22), ('By', 23), ('Carlo', 24), ('Chicago', 25), ('Claude', 26), ('Come', 27), ('Croft', 28), ('Destroyed', 29), ('Devonshire', 30), ('Don', 31), ('Dubarry', 32), ('Emperors', 33), ('Florence', 34), ('For', 35), ('Gallery', 36), ('Gideon', 37), ('Gisburn', 38), ('Gisburns', 39), ('Grafton', 40), ('Greek', 41), ('Grindle', 42), ('Grindles', 43), ('HAD', 44), ('Had', 45), ('Hang', 46), ('Has', 47), ('He', 48), ('Her', 49), ('Hermia', 50), ('His', 51), ('How', 52), ('I', 53), ('If', 54), ('In', 55), ('It', 56), ('Jack', 57), ('Jove', 58), ('Just', 59), ('Lord', 60), ('Made', 61), ('Miss', 62), ('Money', 63), ('Monte', 64), ('Moon-dancers', 65), ('Mr', 66), ('Mrs', 67), ('My', 68), ('Never', 69), ('No', 70), ('Now

In [ ]:
for i, item in enumerate(vocab.items()):
    if i>len(vocab.items())-5:
        print(item)

('your', 1128)
('yourself', 1129)
('<|endoftext|>', 1130)
('<|unk|>', 1131)


In [ ]:
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.int_to_str={ i:s for s,i in vocab.items()}
        self.str_to_int=vocab
    
    def encode(self,text):
        preprocessed= re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed= [ item.strip() for item in preprocessed if item.strip()]
        preprocessed= [
            item if item in self.str_to_int
            else "<|unk|>" for item in preprocessed
    
        ]
        ids= [self.str_to_int[s] for s in preprocessed]
        return ids
    
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.:;?!"()\'])', r'\1', text)
        return text


In [ ]:
tokenizer = SimpleTokenizerV2(vocab)

text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."

text = " <|endoftext|> ".join((text1, text2))

print(text)

Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.


In [ ]:
tokenizer.decode(tokenizer.encode(text))


'<|unk|>, do you like tea? <|endoftext|> In the sunlit terraces of the <|unk|>.'

## BPE

    
    * GPT-2 used BytePair encoding (BPE) as its tokenizer
    
    * it allows the model to break down words that aren't in its predefined vocabulary into smaller subword units or even individual characters, enabling it to handle out-of-vocabulary words
    
    * For instance, if GPT-2's vocabulary doesn't have the word "unfamiliarword," it might tokenize it as ["unfam", "iliar", "word"] or some other subword breakdown, depending on its trained BPE merges
    
    * The original BPE tokenizer can be found here: https://github.com/openai/gpt-2/blob/master/src/encoder.py
    
    * In this chapter, we are using the BPE tokenizer from OpenAI's open-source tiktoken library, which implements its core algorithms in Rust to improve computational performance
    
    * I created a notebook in the ./bytepair_encoder that compares these two implementations side-by-side (tiktoken was about 5x faster on the sample text)

In [ ]:
import importlib
import tiktoken

In [ ]:
tokenizer= tiktoken.get_encoding("gpt2")

In [ ]:

text = (
    "Hello, do you like tea? In the sunlit terraces"
     "of someunknownPlace."
)

ids= tokenizer.encode(text)

ids

[15496,
 11,
 466,
 345,
 588,
 8887,
 30,
 554,
 262,
 4252,
 18250,
 8812,
 2114,
 1659,
 617,
 34680,
 27271,
 13]

In [ ]:
back_to_text= tokenizer.decode(ids)

back_to_text

'Hello, do you like tea? In the sunlit terracesof someunknownPlace.'

In [ ]:
with open("text.txt",'r', encoding='utf-8') as f:
    raw_text= f.read()

encoded_text= tokenizer.encode(raw_text)

In [ ]:
encoded_text[:10]

[40, 367, 2885, 1464, 1807, 3619, 402, 271, 10899, 2138]

In [ ]:
context_size=4

x= encoded_text[:context_size]
y= encoded_text[1:context_size+1]


print(f'x -> {x}')
print(f'y -> {y}')

x -> [40, 367, 2885, 1464]
y -> [367, 2885, 1464, 1807]


In [ ]:
for i in range(1,context_size+1):
    desired= encoded_text[i]
    context= encoded_text[:i]

    print(context, "---->", desired)

[40] ----> 367
[40, 367] ----> 2885
[40, 367, 2885] ----> 1464
[40, 367, 2885, 1464] ----> 1807


In [ ]:
for i in range(1,context_size+1):
    desired= encoded_text[i]
    context= encoded_text[:i]

    print(tokenizer.decode(context), "---->", tokenizer.decode([desired]))

    

I ---->  H
I H ----> AD
I HAD ---->  always
I HAD always ---->  thought


DEPRECATION: Loading egg at c:\python311\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.


DEPRECATION: Loading egg at c:\python311\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:

import torch
print("PyTorch version:", torch.__version__)

PyTorch version: 2.1.1+cpu


## A custom Dataset class must implement three functions: __init__, __len__, and __getitem__. 

In [ ]:
from torch.utils.data import DataLoader, Dataset

class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        token_ids= tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

        for i in range(0,len(token_ids)- max_length,stride):
            input_text= token_ids[i:i+max_length]
            target_text= token_ids[i+1:i+max_length+1]
            self.input_ids.append(torch.tensor(input_text))
            self.target_ids.append(torch.tensor(target_text))

    def __len__(self):
        return len(self.input_ids)
    
    def __getitem__(self, index) :
        return self.input_ids[index], self.target_ids[index]

In [ ]:

def create_dataloader_v1(txt, batch_size=4, max_length=256, stride=128, shuffle=True, drop_last= True, num_workers=0):
    tokenizer=tiktoken.get_encoding("gpt2")
    dataset= GPTDatasetV1(txt, tokenizer, max_length, stride)

    dataloader= DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

In [ ]:
with open("text.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

In [ ]:

dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=1, shuffle=False
)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

TypeError: 'NoneType' object is not iterable

In [ ]:

second_batch = next(data_iter)
print(second_batch)

[tensor([[  287,   262,  6001,   286],
        [  465, 13476,    11,   339],
        [  550,  5710,   465, 12036],
        [   11,  6405,   257,  5527],
        [27075,    11,   290,  4920],
        [ 2241,   287,   257,  4489],
        [   64,   319,   262, 34686],
        [41976,    13,   357, 10915]]), tensor([[  262,  6001,   286,   465],
        [13476,    11,   339,   550],
        [ 5710,   465, 12036,    11],
        [ 6405,   257,  5527, 27075],
        [   11,   290,  4920,  2241],
        [  287,   257,  4489,    64],
        [  319,   262, 34686, 41976],
        [   13,   357, 10915,   314]])]


In [ ]:
third_batch= next(data_iter)
print(third_batch)

[tensor([[  314,  2138,  1807,   340],
        [  561,   423,   587, 10598],
        [  393, 28537,  2014,   198],
        [  198,     1,   464,  6001],
        [  286,   465, 13476,     1],
        [  438,  5562,   373,   644],
        [  262,  1466,  1444,   340],
        [   13,   314,   460,  3285]]), tensor([[ 2138,  1807,   340,   561],
        [  423,   587, 10598,   393],
        [28537,  2014,   198,   198],
        [    1,   464,  6001,   286],
        [  465, 13476,     1,   438],
        [ 5562,   373,   644,   262],
        [ 1466,  1444,   340,    13],
        [  314,   460,  3285,  9074]])]


In [ ]:

dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

TypeError: 'NoneType' object is not iterable

In [ ]:
input_ids = torch.tensor([2, 3, 5, 1])


In [ ]:
vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [ ]:
print(embedding_layer.weight)


Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [ ]:
print(embedding_layer(torch.tensor([3])))


tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [ ]:
print(embedding_layer(input_ids))


tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


In [ ]:

vocab_size = 50257
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [ ]:

max_length = 4
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=False
)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)

In [ ]:

print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)

Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Inputs shape:
 torch.Size([8, 4])


In [ ]:
token_embeddings = token_embedding_layer(inputs)
print(token_embeddings.shape)

torch.Size([8, 4, 256])


In [ ]:

context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)

In [ ]:

pos_embeddings = pos_embedding_layer(torch.arange(max_length))
print(pos_embeddings.shape)

torch.Size([4, 256])


In [ ]:

input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings)


tensor([[[ 2.2288,  0.5619,  0.8286,  ..., -0.6272, -0.2987,  0.8900],
         [ 2.0903, -0.4664, -0.0593,  ...,  0.9115, -1.0493, -1.6473],
         [-0.7158, -0.8304,  1.2494,  ...,  2.3952,  1.8773,  0.8051],
         [ 0.2703,  0.4029,  3.0514,  ...,  0.3595, -1.4548,  0.8310]],

        [[ 3.2835,  1.1749, -1.4150,  ..., -0.3281,  2.4332,  0.6924],
         [-0.2199, -0.9114, -0.1750,  ...,  1.5337, -0.1998,  0.1462],
         [ 1.5197, -1.4240,  0.4391,  ...,  1.0494, -1.4318,  2.3057],
         [ 0.2893,  0.8346, -0.1884,  ...,  1.9602,  0.8709,  0.8796]],

        [[ 0.9662,  0.0952, -0.4640,  ..., -1.0320,  1.6290,  1.7771],
         [ 2.4468, -0.2154,  1.4984,  ...,  1.8766,  0.5595, -0.1423],
         [-0.3856, -2.5393,  1.1556,  ...,  3.6157,  1.3267,  0.4944],
         [-0.2487, -0.5275,  2.0009,  ...,  0.2930,  0.5977,  1.3300]],

        ...,

        [[ 0.1219,  0.3991, -3.2740,  ..., -1.1921,  2.6637,  2.6728],
         [ 1.2438, -1.6436, -1.1101,  ..., -0.7464, -0.98